apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStream
metadata:
  name: openshift-builds-fbc
spec:
  project: openshift-builds-fbc
  template:
    name: openshift-builds-fbc
    values:
      - name: version
        value: 4.15