apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStreamTemplate
metadata:
  name: openshift-builds
spec:
  project: openshift-builds
  variables:
  - name: version
    description: "A version number for a new z-stream"
  - name: versionName
    description: "A K8s-compliant name for the version"
    defaultValue: '{{hyphenize .version}}'
  resources:
  - apiVersion: appstudio.redhat.com/v1alpha1
    kind: Application
    metadata:
      annotations:
        application.thumbnail: "5"
        finalizeCount: "0"
      finalizers:
      - spi.appstudio.redhat.com/remote-secrets
      name: 'openshift-builds-{{.versionName}}'
    spec:
      displayName: 'Red Hat OpenShift Builds {{.version}}'
