apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unit-test
  annotations:
    tekton.dev/title: "Unit Test Task"
spec:
  params:
    - description: The trusted artifact URI containing the application source code.
      name: SOURCE_ARTIFACT
      type: string
    - description: The Trusted Artifact URI pointing to the artifact with the prefetched dependencies.
      name: CACHI2_ARTIFACT
      type: string
    - description: The go command used to run the go unit test
      name: TEST_COMMAND
      type: string
      default: go test ./...
    - description: The Go base image used to run the unit tests
      name: BASE_IMAGE
      type: string
      default: registry.redhat.io/ubi10/go-toolset@sha256:d5d48915a31c7c774caf7568f7fbe3b25275e042f9f4de73d13fba39f9b2a987
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
      # This path is hard coded in the cachi2.env file.
      - mountPath: /cachi2
        name: cachi2
      - name: sealights-credentials
        mountPath: /usr/local/sealights-credentials
    securityContext:
      # This is needed because the different steps in this Task run with different user IDs.
      runAsUser: 0
  steps:
    - image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:59d4997c0d4ebfb2a93f52a942cae109b934c3dcac8a5252639ac8418f070783
      name: use-trusted-artifact
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir/source
        - $(params.CACHI2_ARTIFACT)=/cachi2
    - name: run-tests
      image:  $(params.BASE_IMAGE)
      workingDir: /var/workdir/source
      resources:
        requests:
          memory: 2Gi
          cpu: 1000m
        limits:
          memory: 4Gi
          cpu: 2000m
      script: |
        #!/usr/bin/env sh
        export SEALIGHTS_TOKEN
        SEALIGHTS_TOKEN="$(cat /usr/local/sealights-credentials/token)"
        $(params.TEST_COMMAND)
  volumes:
    - name: workdir
      emptyDir: {}
    - name: cachi2
      emptyDir: {}
    - name: sealights-credentials
      secret:
        secretName: sealights-credentials
