apiVersion: projctl.konflux.dev/v1beta1
kind: Project
metadata:
  name: openshift-builds-fbc
spec:
  displayName: "Red Hat OpenShift Builds Catalog"
  description: |
    Red Hat OpenShift Builds Catalog.
