apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

components:
  - components/openshift-builds-controller
  - components/openshift-builds-git-cloner
  - components/openshift-builds-image-bundler
  - components/openshift-builds-image-processing
  - components/openshift-builds-operator
  - components/openshift-builds-operator-bundle
  - components/openshift-builds-shared-resource
  - components/openshift-builds-shared-resource-webhook
  - components/openshift-builds-waiter
  - components/openshift-builds-webhook

