apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStreamTemplate
metadata:
  name: openshift-builds-fbc
spec:
  project: openshift-builds-fbc
  variables:
  - name: version
    description: "A version number for a new z-stream"
  - name: versionName
    description: "A K8s-compliant name for the version"
    defaultValue: '{{hyphenize .version}}'
  resources:
  - apiVersion: appstudio.redhat.com/v1alpha1
    kind: Application
    metadata:
      name: 'openshift-builds-fbc-{{.versionName}}'
    spec:
      displayName: 'Red Hat OpenShift Builds Catalog {{.version}}'
